name: Scan Secrets

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  scan-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List workspace
        run: ls -R .
        working-directory: ${{ github.workspace }}

      - name: Make script executable
        run: chmod +x scan-secrets.sh
        working-directory: ${{ github.workspace }}

      - name: Run secret scan
        run: ./scan-secrets.sh
        working-directory: ${{ github.workspace }}
